version: 2
updates:
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    groups:
      maven-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    groups:
      docker-minor-and-patch:
        update-types: [minor, patch]
