-- Developments shown on the public "Projects" page and managed from the
-- admin dashboard. Deliberately narrower than `properties`: a project is
-- editorial content (title, blurb, cover image, published flag), whereas a
-- property is a sellable unit with a type, area and price.
--
-- Only `title` is required. Every other descriptive column is nullable so
-- the admin dashboard can save a draft before the full copy exists.

CREATE TABLE projects (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200)                NOT NULL,
    description      TEXT,
    location         VARCHAR(200),
    status           VARCHAR(20),
    price_range      VARCHAR(100),
    cover_image_url  VARCHAR(500),
    published        BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP(6) WITH TIME ZONE
);

-- GET /api/projects filters on published and orders by created_at DESC.
CREATE INDEX idx_projects_published_created_at ON projects (published, created_at);
