-- Who did what in the dashboard, for reading after an incident.
--
-- Admin actions only, and successful ones only. Failed logins, rate-limit
-- hits and probes go to the SECURITY log and the iunu.security.events metric,
-- never here: a row per failed request would turn every flood into a write
-- load on the database. Admin actions are rare, and they are exactly what you
-- need to reconstruct after an account takeover.
--
-- No foreign key to users on purpose: the trail must outlive the account it
-- describes. actor_email is kept alongside actor_id for the same reason.
CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actor_id     BIGINT,
    actor_email  VARCHAR(255),
    action       VARCHAR(48)                 NOT NULL,
    target_type  VARCHAR(32),
    target_id    VARCHAR(64),
    client_ip    VARCHAR(64),
    request_id   VARCHAR(36),
    summary      VARCHAR(500)
);

-- The Activity tab: newest first, optionally filtered by action.
CREATE INDEX idx_audit_log_occurred_at ON audit_log (occurred_at DESC);
-- The new-IP check at admin login: "has this admin signed in from here lately?"
CREATE INDEX idx_audit_log_actor_action ON audit_log (actor_id, action, occurred_at DESC);
